# Generated by Django 5.0 on 2023-12-28 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='', upload_to='profile_picture/'),
        ),
        migrations.AddField(
            model_name='user',
            name='usertype',
            field=models.CharField(default='patient', max_length=100),
        ),
    ]
