# Generated by Django 5.0 on 2024-01-17 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_appointment_appointment_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='Doctor_Profile',
            new_name='doctor_profile',
        ),
    ]
